import type { ChatTabItem, Conversation } from './types';

export const chatTabs: ChatTabItem[] = [
  { key: 'recent', label: 'Recent' },
  { key: 'all', label: 'All' },
  { key: 'favorites', label: 'Favorites' },
];

export const initialFavoriteIds = ['maya', 'arif', 'lina'];

export const initialConversations: Conversation[] = [
  {
    id: 'maya',
    name: 'Maya Rahman',
    title: 'Product designer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'I uploaded the revised onboarding screens.',
    timestamp: '2m',
    unread: 3,
    recent: true,
    lastActive: 900,
  },
  {
    id: 'arif',
    name: 'Arif Chowdhury',
    title: 'Frontend developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'The staging build is ready for QA.',
    timestamp: '8m',
    unread: 1,
    recent: true,
    lastActive: 820,
  },
  {
    id: 'arif3',
    name: 'Arif Chowdhury',
    title: 'Frontend developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'The staging build is ready for QA.',
    timestamp: '8m',
    unread: 1,
    recent: true,
    lastActive: 820,
  },
  {
    id: 'arif2',
    name: 'Arif Chowdhury',
    title: 'Frontend developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'The staging build is ready for QA.',
    timestamp: '8m',
    unread: 1,
    recent: true,
    lastActive: 820,
  },
  {
    id: 'nabila',
    name: 'Nabila Karim',
    title: 'Growth strategist',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Campaign copy is ready for review.',
    timestamp: '24m',
    unread: 0,
    recent: true,
    lastActive: 760,
  },
  {
    id: 'sam',
    name: 'Sam Turner',
    title: 'Project manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Client meeting moved to 11:30.',
    timestamp: '1h',
    unread: 0,
    recent: true,
    lastActive: 650,
  },
  {
    id: 'lina',
    name: 'Lina Ahmed',
    title: 'UX researcher',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Interview notes are now in the shared doc.',
    timestamp: '3h',
    unread: 2,
    recent: false,
    lastActive: 540,
  },
  {
    id: 'lina2',
    name: 'Lina Ahmed',
    title: 'UX researcher',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Interview notes are now in the shared doc.',
    timestamp: '3h',
    unread: 2,
    recent: false,
    lastActive: 540,
  },
  {
    id: 'lina3',
    name: 'Lina Ahmed',
    title: 'UX researcher',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Interview notes are now in the shared doc.',
    timestamp: '3h',
    unread: 2,
    recent: false,
    lastActive: 540,
  },
  {
    id: 'lina4',
    name: 'Lina Ahmed',
    title: 'UX researcher',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Interview notes are now in the shared doc.',
    timestamp: '3h',
    unread: 2,
    recent: false,
    lastActive: 540,
  },
  {
    id: 'lina5',
    name: 'Lina Ahmed',
    title: 'UX researcher',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'Interview notes are now in the shared doc.',
    timestamp: '3h',
    unread: 2,
    recent: false,
    lastActive: 540,
  },
  {
    id: 'jamal',
    name: 'Jamal Hossain',
    title: 'Backend engineer',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    lastMessage: 'API keys were rotated yesterday.',
    timestamp: 'Yesterday',
    unread: 0,
    recent: false,
    lastActive: 420,
  },
];
